spring:
  application:
    name: RatingSystemRest

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url:  jdbc:mysql://mysql:3306/ratingapp
    username: giorgi
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

file:
  upload-dir: wfwadaw

frontend:
  path: http://localhost:3000/

jwt:
  signinkey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
